name: testing
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: setup-node
              uses: actions/setup-node@v3
              with:
                  node-version: '14'

            - name: install dependencies
            - run: yarn

            - name: running test
            - run: yarn run test
